version: 0.2
env:
  variables:
    key: "test"
    key: "value"
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
        - echo Logging in to Amazon ECR...
        - echo ${ECRREPOSITORY} ${REPOSITORYNAME}
        - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECRREPOSITORY
        - REPOSITORY_URI=${ECRREPOSITORY}/${REPOSITORYNAME}
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
        - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_URI}:${IMAGE_TAG} .
      - docker tag ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${REPOSITORY_URI}:${IMAGE_TAG} ${REPOSITORY_URI}:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest
      - echo Writing image definitions file...
      - printf '{"name":"qrcode","imageUri":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files:
      - image*.json
      - appspec.yaml
      - taskdef.json
    secondary-artifacts:
      DefinitionArtifact:
        files:
          - appspec.yaml
          - taskdef.json
      ImageArtifact:
        files:
          - imagedefinitions.json
