AWSTemplateFormatVersion: "2010-09-09"
Description: Template for building ecr registry
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - preprod
      - prod
    Description: EnvironmentName.
  ClusterName:
    Type: String
    Default: Alacrity
  CapacityProviders:
    Type: CommaDelimitedList
    Default:  "FARGATE"
Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders: !Ref CapacityProviders
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 20
      ClusterName: !Ref ClusterName
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Environment
          Value: !Ref Environment
Outputs:
  EcsCluster:
    Description: ECS cluster id
    Value: !Ref EcsCluster
    Export:
      Name: !Sub "${AWS::StackName}-dev"
